spring:
  datasource:
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver

logging:
  level:
    com.jxx: DEBUG

point-source: eth
lucky:
  simple: haha
  banker-min-money: 100000
  game-config:
     - bankType: NN
       gameClass: com.jxx.lucky.domain.NNGame
     - bankType: SN
       gameClass: com.jxx.lucky.domain.PointGame